name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 44.201.144.212 >> ~/.ssh/known_hosts
      
    - name: Deploy to EC2
      run: |
        ssh ec2-user@44.201.144.212 "cd my-app && git pull origin main"
      env:
        EC2_PEM: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
