name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 100.27.28.9 >> ~/.ssh/known_hosts
      
    - name: Setup SSH Keys
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2.pem
        chmod 400 ec2.pem

    - name: Deploy to EC2
      run: |
        ssh -i ec2.pem ec2-user@100.27.28.9 "cd my-app && git stash && git pull origin main"