name: Deploy to Production

on:
  push:
    branches:
      - main  # Ajusta esto a la rama que utilizas para la producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Obfuscate code
      run: npm run obfuscate

    - name: Deploy to AWS EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ec2-user@44.201.144.212
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 400 private_key.pem
        scp -i private_key.pem -r ./dist/* $HOST:my-app
        ssh -i private_key.pem $HOST "cd my-app && git pull && rm -rf ./public/* && mv ./dist/* ./public/"
        rm -f private_key.pem
